### ISSUE TITLE
[CY-4229] `"extends": "@1stg"` is not working correctly

### ISSUE THREAD

**Issue by JounQin** [codacy/codacy-eslint#1393]
```log
Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.6.30 exited with non-zero code 1
Error: Failed to load config "@1stg" to extend from.
Referenced from: /src/package.json
    at configInvalidError (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: '@1stg', importerName: '/src/package.json' }
}

TypeScript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.6.30 exited with non-zero code 1
Error: Failed to load config "@1stg" to extend from.
Referenced from: /src/package.json
    at configInvalidError (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: '@1stg', importerName: '/src/package.json' }
}
```

**Comment by JounQin** [comment]
@franciscodua `@1stg` means `@1stg/eslint-config`, it is public definitely.

**Comment by franciscodua** [comment]
Oh my bad. I thought it was this one https://www.npmjs.com/package/eslint-config-1stg and didn't notice the deprecation note.

We'll check if this is a good candidate for us to add as a plugin and get back to you

**Comment by JounQin** [comment]
@franciscodua I'm not sure what's the difference. 😅

What the word `private` mean in your context? If you mean all custom configs are not supported, then what a pity, configs are very verbose, a lot of users/teams are using their own custom configs.

**Comment by franciscodua** [comment]
By private, I meant not open-source. As in a private repository. I apologize for not being clear on that.

>If you mean all custom configs are not supported, then what a pity, configs are very verbose, a lot of users/teams are using their own custom configs.

Yes. Unfortunately, we don't support custom configurations for now. At this time we try to overcome it by installing common dependencies in our tool.

And we are in the process of adding the one you mentioned in this issue right now!

**Comment by franciscodua** [comment]
Hey @JounQin
This plugin is already installed in our tool. Feel free to check it out
