### ISSUE TITLE
[CY-4313] Add support for eslint-plugin-tsdoc

### ISSUE THREAD

**Issue by prcr** [codacy/codacy-eslint#1423]
Currently, Codacy doesn't support the ESLint plugin [eslint-plugin-tsdoc](https://github.com/microsoft/tsdoc/tree/master/eslint-plugin).

For example, this causes the analysis to fail on https://github.com/prcr/open-scd ([see the logs](https://app.codacy.com/gh/prcr/open-scd/commit?bid=23464361&cid=552288201)):

```
Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.7.11 exited with non-zero code 1
Error: Failed to load plugin 'eslint-plugin-tsdoc' declared in '.eslintrc.cjs': Cannot find module 'eslint-plugin-tsdoc'
Require stack:
- /__placeholder__.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolve (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at /node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:908:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:904:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:725:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/__placeholder__.js' ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-tsdoc',
    resolvePluginsRelativeTo: '/',
    importerName: '.eslintrc.cjs'
  }
}

TypeScript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.7.11 exited with non-zero code 1
Error: Failed to load plugin 'eslint-plugin-tsdoc' declared in '.eslintrc.cjs': Cannot find module 'eslint-plugin-tsdoc'
Require stack:
- /__placeholder__.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolve (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at /node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:908:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:904:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:725:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/__placeholder__.js' ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-tsdoc',
    resolvePluginsRelativeTo: '/',
    importerName: '.eslintrc.cjs'
  }
}
```

**Comment by franciscodua** [comment]
Hi
The `eslint-plugin-tsdoc` is now available to be used in Codacy.
Also, I re-ran the commit in question in Codacy and it no longer has any errors.

I'll close this issue, but you can re-open it or a new one if you still have problems or questions.
