### ISSUE TITLE
[CY-4861] Add support for ESLint plugin '@nrwl/nx'

### ISSUE THREAD

**Issue by nirmalbaralqa** [codacy/codacy-eslint#1737]
Currently Codacy ESLint is failing due to the '@nrwl/nx' plugin.
```Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.15.38 exited with non-zero code 1
Error: Failed to load plugin '@nrwl/nx' declared in 'libs/ui/.eslintrc.json': Cannot find module '@nrwl/eslint-plugin-nx'
Require stack:
- /__placeholder__.js
Referenced from: /src/libs/ui/.eslintrc.json
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolve (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/__placeholder__.js' ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: '@nrwl/eslint-plugin-nx',
    resolvePluginsRelativeTo: '/',
    importerName: 'libs/ui/.eslintrc.json'
  }
}

TypeScript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.15.38 exited with non-zero code 1
Error: Failed to load plugin '@nrwl/nx' declared in 'libs/ui/.eslintrc.json': Cannot find module '@nrwl/eslint-plugin-nx'
Require stack:
- /__placeholder__.js
Referenced from: /src/libs/ui/.eslintrc.json
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolve (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/__placeholder__.js' ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: '@nrwl/eslint-plugin-nx',
    resolvePluginsRelativeTo: '/',
    importerName: 'libs/ui/.eslintrc.json'
  }
}

**Comment by machadoit** [comment]
Hi @nirmalbaralqa it seems that we are not able to support this plugin at this time due to `"@typescript-eslint/parser": "~4.28.3"` at https://github.com/nrwl/nx/blob/master/package.json#L113 since we have `"@typescript-eslint/parser": "^4.29.2",`.

We are not going to lower the parser version for now, so we will wait for the nx-plugin to update the parser version to 4.29.2+. Sorry for the problems that this might cause, but for now, either you configure Codacy on the UI, or remove the plugin form the configuration file

**Comment by franciscodua** [comment]
Closing this issue since we're not tackling this now

**Comment by danielkresta** [comment]
Any news on this? Adding @nrwl/nx would be useful for us.
