### ISSUE TITLE
[CY-5029] Add support for eslint-plugin-i18n-json

### ISSUE THREAD

**Issue by rohit-gohri** [codacy/codacy-eslint#1906]
Ref: https://www.npmjs.com/package/eslint-plugin-i18n-json

Error:

```
Javascript :

KubernetesDockerRunner: Container for codacy/codacy-eslint:6.22.0 exited with non-zero code 1
Error: Failed to load plugin 'i18n-json' declared in '.eslintrc#overrides[2]': Cannot find module 'eslint-plugin-i18n-json'
Require stack:
- /__placeholder__.js
Referenced from: /src/.eslintrc
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolve (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/__placeholder__.js' ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-i18n-json',
    resolvePluginsRelativeTo: '/',
    importerName: '.eslintrc#overrides[2]'
  }
}

```

**Comment by rohit-gohri** [comment]
Closed in #1907
